### ISSUE TITLE
Problems with parallelization in mlr

### ISSUE THREAD

**Issue by studerus** [berndbischl/parallelMap#21] opened 2014-07-18 16:24 UTC
When I cancel a runing parallel task using escape and the restart the task again, I often get the following error:
```
Error in !v : invalid argument type
```

With traceback I get the following:
```
4: FUN(X[[2L]], ...)
3: lapply(oks, function(v) {
       names(v)[!v]
   })
2: parallelLibrary("mlr", master = FALSE, level = "mlr.resample", 
       show.info = FALSE)
1: resample(over.wrap, task, outer, measures = meas, extract = getTuneResult)
```

If I run parallelStop() and parallelStartSocket(4) it works again. It seems that something is not properly cleaned up if a paralel task is cancelled.

Here's my sessionInfo():
```
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] LiblineaR_1.80-7 parallelMap_1.1  mlr_2.1          BBmisc_1.7       ParamHelpers_1.3 studerus_0.1-1  

loaded via a namespace (and not attached):
[1] checkmate_1.1   codetools_0.2-8 splines_3.1.1   survival_2.37-7 tools_3.1.1  
```

**Comment by berndbischl** [comment] 2015-01-27 04:49
I do not get this and cannot reproduce this.

Also, judging from the traceback this would be an internal issue of parallel.

Closing for now, if problems reappear, please open again.

**Closed by berndbischl** 2015-01-27 04:49 UTC

**Comment by 579amal** [comment] 2018-04-04 03:46
Same happens to me. If I cancel Parallel and Parallel Map by unticking in packages, my code gives the error "Error in !v : invalid argument type". But when I use this code : 
parallelStop()
parallelStartSocket(4)

it runs again. Thanks, @studerus for that solution.
